//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.OrderT = new HashSet<OrderT>();
        }
    
        public int payment_id { get; set; }
        public string cart_name { get; set; }
        public int cart_num { get; set; }
        public int cartexpmo { get; set; }
        public int cartexpyr { get; set; }
        public byte cvv { get; set; }
        public bool payment_allowed { get; set; }
        public int customer_no { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderT> OrderT { get; set; }
    }
}
